# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170426_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='iamge',
            new_name='image',
        ),
    ]
