# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notice',
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
