# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170531_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResourse',
            new_name='CourseResources',
        ),
    ]
