# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170427_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1),
        ),
    ]
